### ISSUE TITLE
Boot error

### ISSUE THREAD

**Issue by Pythnlearner** [adrianjagielak/HP-Elitebook-850-G7-Hackintosh#1]
![f1d15215921517b3.jpg](https://user-images.githubusercontent.com/66311873/147753237-1843c9fc-f98d-4aad-b0cc-4ac510687351.jpg)

Any solutions and suggestions on this ? And my trackpad on 840 G7 not working.. all other working .. used another EFI .. will you help me on this.

**Comment by Pythnlearner** [comment]
Now it worked.

**Comment by Pythnlearner** [comment]
Solved

**Comment by adrianjagielak** [comment]
How did you solved this?
