### ISSUE TITLE
Getting sleep to work

### ISSUE THREAD

**Issue by Haniasita** [adrianjagielak/HP-Elitebook-850-G7-Hackintosh#4]
Hello there,

I've been using this successfully to run macOS Monterey on my own 850 G7. I've updated kexts manually and did a couple of edits in the config, and it's all running beautifully. Thank you very much for this!

My question is this : Do you know what's preventing sleep from working? Or alternatively, do you have any pointers as to what it might be?

Having to do a full shutdown and then a full boot every single time I want to use the computer doesn't really feel natural at all. There's got to be a way to fix this. I assume you looked into this yourself, hence why I'm asking.

As specified in the Dortania guide, I've already tried adding boot arguments such as igfxonln=1, and I've tried swapping to a different backlight SSDT-PNLF, to no avail.

Thank you for your time.

**Comment by Haniasita** [comment]
[This repo](https://github.com/tomaximoto/Elitebook-G7) claims to have sleep working on a 840 G7, I'll look further into it as in theory it should also work for a 850 G7.

**Comment by Haniasita** [comment]
[This Reddit post](https://www.reddit.com/r/hackintosh/comments/lxqhg5/hp_elitebook_840_g7/) claims to have gotten sleep to work on a 840 G7 thanks to Hackintool. I'll test this out later tonight and report back if it succeeds.

**Comment by adrianjagielak** [comment]
Hi,
Sorry for the late reply.

Congratulations on managing to get Monterey working! Do you mind If I include your changes in this repo?

I don't have any pointers as to what's preventing sleep from working unfortunately, other than googling what you will find in logs. I've given up on this a long time ago as it's not my primary device anyway but I hope you will find something out.

I've seen this Reddit post and repo you've sent back in the day as it was mentioned in [this tonymac thread](https://www.tonymacx86.com/threads/hp-elitebook-840-g7-last-mile.309418) (i believe it was the first thread on the internet about this laptop in the context of Hackintoshing and was very helpful when creating my EFI) but all of the information I could find was about 840 G7 and I assumed there are some slight changes between 840 G7 and 850 G7 that can cause problems in things like sleep.

I've personally made some Reddit posts about this laptop before ([850 G7 Big Sur](https://www.reddit.com/r/hackintosh/comments/maoxmy/big_sur_1123_success_on_my_hp_elitebook_850_g7), [850 G7 Monterey](https://www.reddit.com/r/hackintosh/comments/nv23bw/just_updated_my_hp_elitebook_850_g7_to_macos_12)) (yeah, I've managed to get Monterey Beta on this before, then downgraded to Big Sur, then lost updated EFI) but I don't think you will find something useful there.

**Comment by Haniasita** [comment]
All good, I don't always answer quick either.

Sure, I'll share my changes once I'm happy with how things are going. There are a few things that aren't working :
- The USB-A port on the right does not work
- Brightness keys do not work
- Bluetooth does not work (Likely just an edit needed in the config.plist)
- Sleep does not work (Of course)
Once I'll get at least a couple of these working again, I'll be ready to share my changes.
The biggest step towards installing Monterey was simply updating OpenCore to the latest version.

Thank you for the information, I'll read trough it thoroughly.

I'll attempt to import some sleep patches into the config.plist and see if that changes anything.

**Comment by Haniasita** [comment]
Hello again,

I was not successful in enabling sleep on my 850 G7, and sadly likely won't ever do so, as I've traded this computer for an actual MacBook Pro. 

This was not the note I was hoping to end on, so at the very least, I've attached my updated EFI regardless. Please note that this still has the issues I mentioned in my previous post. I could not attach it in my post, so I've put it up here instead, I hope you don't mind : https://mega.nz/file/6cRzxDLI#O1w3DrT-hlLjpR_yrBGqM71MZUmL9mFjEAa8GSOLirw
It is basically just the EFI on this page, with a couple of tweaks and a bunch of updates.

I wish good luck on future hackintosh endeavors!
